pipeline {
    agent any
    stages { 
        stage('gitcheckout') {
            checkout scmGit(
                branches: [[
                    name: '*/master']], 
                    userRemoteConfigs: [[
                        credentialsId: 'github_creditial', 
                        url: 'https://github.com/Likihes/Docker_course.git'
                        ]]
                        )
        
    }
    
         stage('build')
         {

         }
    }
}